// Code generated by mockery v2.3.0. DO NOT EDIT.

package downloader

import mock "github.com/stretchr/testify/mock"

// MockMediaScanner is an autogenerated mock type for the MediaScanner type
type MockMediaScanner struct {
	mock.Mock
}

// ScanLibraries provides a mock function with given fields:
func (m *MockMediaScanner) ScanLibraries() error {
	args := m.Called()
	return args.Error(0)
}

// GivenScanLibrariesFails ...
func (m *MockMediaScanner) GivenScanLibrariesFails(reason error) *MockMediaScanner {
	m.On("ScanLibraries").Return(reason)
	return m
}

// GivenScanLibrariesSucceeds ...
func (m *MockMediaScanner) GivenScanLibrariesSucceeds() *MockMediaScanner {
	m.On("ScanLibraries").Return(nil)
	return m
}
