package downloader

import (
	"github.com/plexpi/download_service/bittorrent"
	mock "github.com/stretchr/testify/mock"
)

// MockBittorrentAPI is an autogenerated mock type for the BittorrentAPI type
type MockBittorrentAPI struct {
	mock.Mock
}

// AddTorrent provides a mock function with given fields: url, category
func (m *MockBittorrentAPI) AddTorrent(params bittorrent.AddTorrentParams) error {
	args := m.Called(params)
	return args.Error(0)
}

// GivenAddTorrentFails ...
func (m *MockBittorrentAPI) GivenAddTorrentFails(reason error) *MockBittorrentAPI {
	m.On("AddTorrent", mock.Anything).Return(reason)
	return m
}

// GivenAddTorrentSucceeds ...
func (m *MockBittorrentAPI) GivenAddTorrentSucceeds() *MockBittorrentAPI {
	m.On("AddTorrent", mock.Anything).Return(nil)
	return m
}
