name: CI

on:
  pull_request:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'

    - name: Install dependencies
      run: |
        go mod download 
      
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
          version: v1.29
    
    - name: Run tests
      run: go test ./...
