name: CI

on:
pull_request:
    branches:
    - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15

    - name: Install dependencies
      run: |
        go mod download 
      
    - name: Run lint
      run: |
        golint ./...
    
    - name: Run tests
      run: go test ./...
