name: CI

on:
  pull_request:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'

    - name: Install dependencies
      run: go mod download 
      
    - name: Lint
      run: |
        GOBIN=$PWD/bin go install golang.org/x/lint/golint
        ./bin/golint ./...
    
    - name: Run tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    
    - name: Codecov
      uses: codecov/codecov-action@v1.0.14
      with:
        token: ${{ secret.CODECOV_TOKEN }}
        file: "./coverage.txt"
        fail_ci_if_error: true
